# Generated by Django 5.2.7 on 2025-10-26 08:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Corredor')),
                ('codigo_corredor', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(help_text='Código del instrumento. Ej: ACN', max_length=50, verbose_name='Instrumento')),
                ('fecha', models.DateField(help_text='Fecha en formato AAAA-MM-DD', verbose_name='Fecha')),
                ('secuencia', models.IntegerField(help_text='Número de secuencia', verbose_name='Secuencia')),
                ('numero_dividendo', models.IntegerField(verbose_name='Número de dividendo')),
                ('tipo_sociedad', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1, verbose_name='Tipo Sociedad')),
                ('valor_historico', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Histórico')),
                ('factor_8', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_9', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_10', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_11', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_12', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_13', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_14', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_15', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_16', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_17', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_18', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_19', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_20', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_21', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_22', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_23', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_24', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_25', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_26', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_27', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_28', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_29', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_30', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_31', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_32', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_33', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_34', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_35', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_36', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_37', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.corredor', verbose_name='Corredor')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-fecha', 'instrumento'],
            },
        ),
    ]
