# Generated by Django 5.2.7 on 2025-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='instrumento_no_inscrito',
            field=models.BooleanField(default=False, verbose_name='Instrumento No Inscrito'),
        ),
    ]
