# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_calificaciontributaria_instrumento_no_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='acogido_isfut',
            field=models.BooleanField(default=False, verbose_name='Acogido a Isfut/Isift'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='descripcion_dividendo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del Dividendo'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Factor de Actualización'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='origen',
            field=models.CharField(choices=[('COR', 'Corredora'), ('SIS', 'Sistema')], default='SIS', max_length=3, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='tipo_mercado',
            field=models.CharField(blank=True, choices=[('ACC', 'Acciones'), ('CFI', 'CFI'), ('FFM', 'Fondos Mutuos')], max_length=3, null=True, verbose_name='Tipo de Mercado'),
        ),
    ]
