# Generated by Django 5.2.7 on 2025-11-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_calificaciontributaria_acogido_isfut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='fuente_ingreso',
            field=models.CharField(choices=[('MAN', 'Ingreso Manual'), ('FAC', 'Carga Factores'), ('MON', 'Carga Montos')], default='MAN', max_length=3, verbose_name='Fuente de Ingreso'),
        ),
    ]
